//! Payload specifications generated from the OpenADR enumeration schemas.
//!
//! **Generated file — do not edit.** Regenerate with `cargo xtask codegen` after updating
//! `specs/openadr3-specification/<version>/enumerations/*.schema.yaml`.
//!
//! All six enumeration files are read: the four that describe a `valuesMap` become
//! [`PAYLOAD_SPECS`], and the two that constrain a descriptor field become string tables.

use super::{PayloadGroup, PayloadSpec, ValueKinds};
use rust_decimal_macros::dec;

/// Every payload type the specification enumerates, in name order within each group.
pub(super) static PAYLOAD_SPECS: &[PayloadSpec] = &[
    PayloadSpec {
        name: "ALERT_AIR_QUALITY",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_BLACK_START",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_FIRE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_FLEX_ALERT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_FREEZING",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_GRID_EMERGENCY",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_OTHER",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_POSSIBLE_OUTAGE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_TSUNAMI",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "ALERT_WIND",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CHARGE_STATE_SETPOINT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CONTROL_LEVEL_OFFSET",
        group: PayloadGroup::Event,
        kinds: ValueKinds::INTEGER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(-10)),
        maximum: Some(dec!(10)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CONTROL_LEVEL_OFFSET_PERCENT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(-1)),
        maximum: Some(dec!(1)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CONTROL_SETPOINT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::ANY,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "CTA2045_REBOOT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::INTEGER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: Some(dec!(1)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CTA2045_SET_OVERRIDE_STATUS",
        group: PayloadGroup::Event,
        kinds: ValueKinds::INTEGER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: Some(dec!(1)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "CURVE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::POINT,
        min_items: 1,
        max_items: None,
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DISPATCH_INSTRUCTION",
        group: PayloadGroup::Event,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: None,
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "DISPATCH_SETPOINT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DISPATCH_SETPOINT_RELATIVE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_AVAILABLE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_AVAILABLE_PRICE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_LIMIT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_RESERVATION",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_RESERVATION_FEE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_CAPACITY_SUBSCRIPTION",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_PRICE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "GHG",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_AVAILABLE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_AVAILABLE_PRICE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_LIMIT",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_RESERVATION",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_RESERVATION_FEE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_CAPACITY_SUBSCRIPTION",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "OLS",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: None,
        minimum: Some(dec!(0)),
        maximum: Some(dec!(1)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "PRICE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "PRICE_ALTERNATE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "SIMPLE",
        group: PayloadGroup::Event,
        kinds: ValueKinds::INTEGER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: Some(dec!(3)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "BINDING_EVENTS",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::BOOLEAN,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "COUNTRY",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "LOCAL",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::BOOLEAN,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "PRINCIPAL_SUBDIVISION",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "PROGRAM_LONG_NAME",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "PROGRAM_TYPE",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "RETAILER_LONG_NAME",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "RETAILER_NAME",
        group: PayloadGroup::ProgramAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "BASELINE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DATA_QUALITY",
        group: PayloadGroup::Report,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &["OK", "MISSING", "ESTIMATED", "BAD"],
    },
    PayloadSpec {
        name: "DELTA_USAGE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DEMAND",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DOWN_REGULATION_AVAILABLE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_RESERVATION_CAPACITY",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "EXPORT_RESERVATION_FEE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "GENERATION_DELTA_AVAILABLE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_RESERVATION_CAPACITY",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "IMPORT_RESERVATION_FEE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "LOAD_SHED_DELTA_AVAILABLE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "OPERATING_STATE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[
            "NORMAL",
            "ERROR",
            "IDLE_NORMAL",
            "RUNNING_NORMAL",
            "RUNNING_CURTAILED",
            "RUNNING_HEIGHTENED",
            "IDLE_CURTAILED",
            "SGD_ERROR_CONDITION",
            "IDLE_HEIGHTENED",
            "IDLE_OPTED_OUT",
            "RUNNING_OPTED_OUT",
            "AGGREGATED_REPORT",
        ],
    },
    PayloadSpec {
        name: "READING",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "REGULATION_SETPOINT",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "SETPOINT",
        group: PayloadGroup::Report,
        kinds: ValueKinds::ANY,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "SIMPLE_LEVEL",
        group: PayloadGroup::Report,
        kinds: ValueKinds::INTEGER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: Some(dec!(3)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "STORAGE_CHARGE_LEVEL",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: Some(dec!(1)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "STORAGE_DISPATCH_FORECAST",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "STORAGE_MAX_CHARGE_POWER",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "STORAGE_MAX_DISCHARGE_POWER",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "STORAGE_USABLE_CAPACITY",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "UP_REGULATION_AVAILABLE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "USAGE",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "USAGE_FORECAST",
        group: PayloadGroup::Report,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "AREA",
        group: PayloadGroup::VenAttribute,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: None,
        minimum: None,
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "DESCRIPTION",
        group: PayloadGroup::VenAttribute,
        kinds: ValueKinds::STRING,
        min_items: 1,
        max_items: Some(1),
        minimum: None,
        maximum: None,
        min_length: Some(1),
        max_length: Some(128),
        allowed: &[],
    },
    PayloadSpec {
        name: "LOCATION",
        group: PayloadGroup::VenAttribute,
        kinds: ValueKinds::NUMBER,
        min_items: 2,
        max_items: Some(2),
        minimum: Some(dec!(-180)),
        maximum: Some(dec!(180)),
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "MAX_POWER_CONSUMPTION",
        group: PayloadGroup::VenAttribute,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
    PayloadSpec {
        name: "MAX_POWER_EXPORT",
        group: PayloadGroup::VenAttribute,
        kinds: ValueKinds::NUMBER,
        min_items: 1,
        max_items: Some(1),
        minimum: Some(dec!(0)),
        maximum: None,
        min_length: None,
        max_length: None,
        allowed: &[],
    },
];

/// Every unit of measure `eventPayloadDescriptor.units` enumerates.
pub(super) static UNITS: &[&str] = &[
    "KWH",
    "THERMS",
    "GHG",
    "VOLTS",
    "AMPS",
    "CELSIUS",
    "FAHRENHEIT",
    "PERCENT",
    "KW",
    "KVAH",
    "KVARH",
    "KVA",
    "KVAR",
];

/// Every reading type `reportPayloadDescriptor.readingType` enumerates.
pub(super) static READING_TYPES: &[&str] = &[
    "DIRECT_READ",
    "ESTIMATED",
    "SUMMED",
    "MEAN",
    "PEAK",
    "FORECAST",
    "AVERAGE",
    "NORMAL",
    "ERROR",
];
